name: ehr_report
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  fl_chart: ^0.63.0
  cupertino_icons: ^1.0.8 
  percent_indicator: ^4.2.2
  flutter_rating_bar: ^4.0.0
  equatable: ^2.0.5
  shared_preferences: ^2.3.5
  # platform_device_id: ^1.0.1
  device_info_plus: ^11.2.0
  package_info_plus: ^8.1.2
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.2.10
  safe_device: ^1.2.0
  get: ^4.6.6
  http: ^1.2.2
  image_picker: ^1.1.2
  firebase_messaging: ^15.2.0
  awesome_dialog: ^3.2.1
  firebase_crashlytics: ^4.3.0
  intl: ^0.18.0
  flutter_launcher_icons: ^0.11.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/images/iconehrreportss.png
  - assets/images/ehrreport.png
  - assets/images/fotologin.png
  - assets/images/logo.png
  - assets/images/profile.jpeg
  - assets/images/login.png
  - assets/images/lgn.png
  - assets/images/bungakanan.png
  - assets/images/bungakiri.png
  - assets/images/kpi.png
  - assets/images/cuti.png
  - assets/images/kunjungan.png
  - assets/images/lembur.png
  - assets/images/absensi.png
  - assets/images/masuk.png
  - assets/images/exam.png
  - assets/images/library.png
  - assets/images/lembur.jpg
  - assets/images/aisyah.jpg
  - assets/images/bastian.jpg
  - assets/images/bella.jpg
  - assets/images/bryan.jpg
  - assets/images/gigi.jpg
  - assets/images/hadid.jpg
  - assets/images/haryo.jpg
  - assets/images/iqbal2.jpg
  - assets/images/mawareva.jpg
  - assets/images/vino.jpg
  - assets/images/def_img.png
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/iconehrreportss.png"